# Generated by Django 5.0.3 on 2024-05-14 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_checklist_proto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='self_checklist_proto.surveyoption')),
            ],
        ),
        migrations.DeleteModel(
            name='UserSurveyOption',
        ),
    ]
