# Generated by Django 5.0.3 on 2024-05-27 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_checklist_proto', '0002_surveyresult_delete_usersurveyoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='self_checklist_proto.survey')),
            ],
        ),
        migrations.AddField(
            model_name='surveyresult',
            name='submission',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='self_checklist_proto.surveysubmission'),
            preserve_default=False,
        ),
    ]
